dataroot: "data/gso_turtle_my_render/"
model: 
  gpu_idx: 0
  model_config: "configs/sd-objaverse-finetune-c_concat-256.yaml"
  ckpt: "../105000.ckpt"
  n_samples: 1
  lr: 3e-4
  lr_scheduler:
    use: False
    milestones: [200]
    gamma: 0.2
input:
  ref_image: "elev=0_azi=0.png"
  target_image: "elev=0_azi=15.png"
  rel_elev: 0.0
  rel_azi: 0.0
  rel_radius: 0.0
  max_index: 7
  min_index: null
log:
  log_root: "../runs/loss_check_all"
  run_name: "turtle_clamp_step5_index7"
  # log_all_img: True
  # log_all_img_freq: 10
comment: ""
check_range: [-180, 180]
check_step: 5