dataroot: "data/gso_myrendering/Circo_Fish_Toothbrush_Holder_rot"
model: 
  gpu_idx: 0
  model_config: "configs/sd-objaverse-finetune-c_concat-256.yaml"
  ckpt: "../zero123-xl.ckpt"
  # ckpt: "../105000.ckpt"
  n_samples: 1
  loss_type: "BluredMaskImgX0" # for logging
  loss_amp: 1
  lr: 1e-3
  lr_scheduler:
    use: False
    milestones: [200]
    gamma: 0.2
  guide_scale: 1.0
  ddim_eta: 1.0
  blur_k_size: 9
  blur_min: null
  blur_max: 3
  clamp: null
input:
  ref_image: "0_0.png"
  target_image: "-20_0.png"
  rel_elev: 0.0
  rel_azi: 0.0
  rel_radius: 0.0
  max_index: 35
  min_index: null
  input_type: "perfect" # for logging
group_name: "PerfectInput_normal"
run_name: "idx35_elev"
log_all_img: True
comment: "no uc for noise loss, add logvar, scale1"
check_type: "elev"
check_range: [-30, 30]
check_step: 1
