dataroot: "data/gso_turtle_my_render/"
model: 
  gpu_idx: 0
  model_config: "configs/sd-objaverse-finetune-c_concat-256.yaml"
  ckpt: "../zero123-xl.ckpt"
  # ckpt: "../105000.ckpt"
  n_samples: 1
  loss_type: "BluredMaskImgX0" # for logging
  loss_amp: 1
  lr: 1e-3
  lr_scheduler:
    use: False
    milestones: [200]
    gamma: 0.2
  guide_scale: 3.0
  ddim_eta: 1.0
  blur_k_ize: 3
  blur_min: 0.5
  blur_max: 2.0
  clamp: null
input:
  ref_image: "elev=0_azi=0.png"
  target_image: "elev=0_azi=20.png"
  rel_elev: 0.0
  rel_azi: 0.0
  rel_radius: 0.0
  max_index: 45
  min_index: 1
  input_type: "perfect" # for logging
group_name: "PerfectInput_normal_idxsweep"
run_name: "xl_blur.5-2_noclamp"
log_all_img: True
comment: ""
check_range: [-45, 45]
check_step: 1
