# dataroot: "data/gso_myrendering/Circo_Fish_Toothbrush_Holder_rot"
dataroot: "data/gso_myrendering/Circo_Fish_Toothbrush_Holder"
model: 
  gpu_idx: 0
  model_config: "configs/sd-objaverse-finetune-c_concat-256.yaml"
  ckpt: "../zero123-xl.ckpt"
  # ckpt: "../105000.ckpt"
  n_samples: 1
  loss_type: "BluredMaskImgX0" # for logging
  lr: 1e-1
  lr_scheduler:
    use: True
    type: ReduceLROnPlateau
    gamma: 0.7
    patience: 10
  guide_scale: 1.0
  ddim_eta: 1.0
  blur_k_size: 9
  blur_min: null
  blur_max: 3
  iters: 100
  clamp: null
input:
  # ref_image: "elev=0_azi=0.png"
  # target_image: "elev=0_azi=40.png"
  ref_image: "0_0_0.00.png"
  target_image: "-10_10_0.29.png"
  rel_elev: 0.0
  rel_azi: 0.0
  rel_radius: 0.0
  max_index: 35
  min_index: 20
  input_type: "perfect" # for logging
group_name: "PerfectInput"
run_name: "Idx35-20_all_norecenter_rescale_dist_search2"
log_all_img: False
log_all_img_freq: 10
comment: "ReduceLROnPlateau, xl_Blurk9_3_idx35_BlurMaskImgX0"
train_type: "all"
