# dataroot: "data/gso_turtle_my_render/"
dataroot: "data/gso_myrendering/Circo_Fish_Toothbrush_Holder"
model: 
  gpu_idx: 0
  model_config: "configs/sd-objaverse-finetune-c_concat-256.yaml"
  ckpt: "../zero123-xl.ckpt"
  # ckpt: "../105000.ckpt"
  n_samples: 1
  loss_type: "BluredMaskImgX0" # for logging
  lr: 3e-3
  lr_scheduler:
    use: False
    milestones: [200]
    gamma: 0.2
  guide_scale: 1.0
  ddim_eta: 1.0
  blur_k_size: 9
  blur_min: null
  blur_max: 3
  iters: 500
  clamp: null
input:
  # ref_image: "elev=0_azi=0.png"
  # target_image: "elev=0_azi=40.png"
  ref_image: "0_0.png"
  target_image: "-20_0.png"
  rel_elev: 0.0
  rel_azi: 0.0
  rel_radius: 0.0
  max_index: 55
  min_index: null
  input_type: "perfect" # for logging
group_name: "PerfectInput"
run_name: "Blurk9_3_idx55_rot"
log_all_img: False
log_all_img_freq: 10
comment: "xl_Blurk9_3_idx35_BlurMaskImgX0"
