seed: 42
gpu_idx: 0
data:
  root: data
  dataset_name: GSO
  obj: 3D_Dollhouse_Happy_Brother
  idx: [0,1]

  # train
  image_dir: ${data.root}/${data.dataset_name}/${data.obj}/train/rgb
  gt_transform_fp: ${data.root}/${data.dataset_name}/${data.obj}/train/transform.json
  ref_image_path: ${data.image_dir}/${data.idx[0]}.png
  target_image_path: ${data.image_dir}/${data.idx[1]}.png

  # test
  test_image_dir: ${data.root}/${data.dataset_name}/${data.obj}/test/rgb
  test_transform_fp: ${data.root}/${data.dataset_name}/${data.obj}/test/transform.json

  # experiment
  # exp_root_dir: exp
  # exp_dir: ${data.exp_root_dir}/${data.dataset_name}/${data.obj}/${data.idx}
  # transform_fp: ${data.exp_dir}/transform.json
  # lora_ckpt_fp: ${data.exp_dir}/lora.ckpt
  # demo_fp:  ${data.exp_dir}/demo.png
model:
  model_config: "configs/sd-objaverse-finetune-c_concat-256.yaml"
  ckpt: "../zero123-xl.ckpt"
optim:
  iters: 100
  loss_type: "BluredMaskImgX0" # for logging
  lr: 1e-1
  lr_scheduler:
    type: ReduceLROnPlateau
    gamma: 0.6
    patience: 10
args:
  n_samples: 1
  guide_scale: 1.0
  ddim_steps: 75
  ddim_eta: 1.0
  blur_k_size: 9
  blur_min: null
  blur_max: 3
  mask_init_size: 1.25
input:
  dualway: True
  init_pose: [[0, 0, 0], [0, 90, 0], [0, 180, 0], [0, -90, 0]]
  rel_elev: 0.0
  rel_azi: 0.0
  rel_radius: 1.0
  max_index: 75
  min_index: 0
  input_type: "perfect" # for logging
group_name: "Eval"
run_name: "Idx75-0_dualway_noema_noclip_originbg"
log_all_img: False
log_all_img_freq: 10
comment: "noclip on tarce when calculate err, no ema on choosing answer, 5obj_c3, search"
train_type: "all"
#NoiseLoss
#BluredMaskImgX0