dataroot: "data/gso_turtle_my_render/"
model: 
  gpu_idx: 1
  model_config: "configs/sd-objaverse-finetune-c_concat-256.yaml"
  ckpt: "../105000.ckpt"
  lr: 3e-4
  lr_scheduler:
    use: False
    milestones: [200]
    gamma: 0.2
  update_input_freq: 50
input:
  ref_image: "elev=0_azi=0.png"
  target_image: "elev=0_azi=10.png"
  rel_elev: 0.0
  rel_azi: 0.0
  rel_radius: 0.0
log:
  log_root: "../runs/prograssiveInput_index35-0_azi"
  run_name: "turtle_lr3e-4"
  log_all_img: True
  log_all_img_freq: 50
comment: ""