data:
  dataroot: data
  dataset_name: GSO
  obj_idx: 0
model: 
  gpu_idx: 0
  model_config: "configs/sd-objaverse-finetune-c_concat-256.yaml"
  ckpt: "../zero123-xl.ckpt"
args:
  n_samples: 1
  loss_type: "BluredMaskImgX0" # for logging
  lr: 1e-1
  lr_scheduler:
    type: ReduceLROnPlateau
    gamma: 0.7
    patience: 10
  guide_scale: 1.0
  ddim_eta: 1.0
  blur_k_size: 9
  blur_min: null
  blur_max: 3
  iters: 100
  clamp: null
input:
  rel_elev: 0.0
  rel_azi: 0.0
  rel_radius: 0.0
  max_index: 35
  min_index: 20
  input_type: "perfect" # for logging
group_name: "PerfectInput"
run_name: "Blurk9_3_idx35-20_all"
log_all_img: False
log_all_img_freq: 10
comment: "ReduceLROnPlateau, xl_Blurk9_3_idx35_BlurMaskImgX0"
train_type: "all"
